#!/usr/bin/env bash
# build-ios-game-modules.sh — build openQ4's SP and MP game modules as embedded
# signed dylibs for iOS (DECISIONS D-014).
#
#   scripts/build-ios-game-modules.sh [device|sim|visionos|visionos-sim] [sp|mp|both]
#
#   -> build/{ios,ios-sim,visionos,visionos-sim}/modules/game-sp_arm64.dylib
#                              /game-mp_arm64.dylib
#
# These are dylibs, not static archives, deliberately. iOS permits dlopen of
# bundle-resident code signed with the app, so upstream's loader — trusted-root
# search, breadcrumbs, live SP<->MP switching — runs unmodified. The alternative
# (static linking) would mean undefining __DOOM_DLL__, which silently disables
# BSE and changes what the game code is. See D-014.
#
# SP and MP each get their OWN idlib build: precompiled.h includes a different
# Game_local.h under -DGAME_MPAPI, so the same type names carry different
# definitions (meson.build:1344-1350). They are kept apart at runtime by hidden
# visibility + upstream's one-symbol export list + RTLD_LOCAL — upstream's own
# solution to this, see tools/build/darwin_game_module.exp and issue #90.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TREE="$ROOT/build/src-ios"
STAGE="$TREE/.tmp/gamelibs_stage"
GEN="$ROOT/build/ios-gen"
DEPS_BASE="$ROOT/build"
IOS_MIN=16.0
# 2.5, not 2.0: the prebuilt MoltenVK xrOS slices are stamped minos 2.5 (D-090).
XROS_MIN=2.5
JOBS="$(sysctl -n hw.ncpu)"

LANE="${1:-device}"
WHICH="${2:-both}"
case "$LANE" in
	device)       SDKNAME=iphoneos        ; OUT="$ROOT/build/ios"           ; DEPS="$DEPS_BASE/ios-deps" ;;
	sim)          SDKNAME=iphonesimulator ; OUT="$ROOT/build/ios-sim"       ; DEPS="$DEPS_BASE/ios-sim-deps" ;;
	visionos)     SDKNAME=xros            ; OUT="$ROOT/build/visionos"      ; DEPS="$DEPS_BASE/visionos-deps" ;;
	visionos-sim) SDKNAME=xrsimulator     ; OUT="$ROOT/build/visionos-sim"  ; DEPS="$DEPS_BASE/visionos-sim-deps" ;;
	*) echo "usage: $0 [device|sim|visionos|visionos-sim] [sp|mp|both]" >&2; exit 1 ;;
esac
case "$LANE" in
	device)       TARGET_FLAGS=( -arch arm64 -miphoneos-version-min="$IOS_MIN" ) ;;
	sim)          TARGET_FLAGS=( -target "arm64-apple-ios${IOS_MIN}-simulator" ) ;;
	visionos)     TARGET_FLAGS=( -target "arm64-apple-xros${XROS_MIN}" ) ;;
	visionos-sim) TARGET_FLAGS=( -target "arm64-apple-xros${XROS_MIN}-simulator" ) ;;
esac

[ -d "$STAGE/src/game" ] || { echo "FATAL: run scripts/sync-overlay.sh first" >&2; exit 1; }

SDK="$(xcrun --sdk "$SDKNAME" --show-sdk-path)"
CXX="$(xcrun --sdk "$SDKNAME" -f clang++)"
MODOUT="$OUT/modules"
mkdir -p "$MODOUT" "$OUT/gameobj" "$OUT/gamelogs"

# The modules' BUILD_NUMBER comes from openq4_version_generated.h, and every
# savegame the game writes carries it; a module built against a different header
# than the engine refuses its own saves (D-066). Refresh the shared header from
# the pin, then stamp what we compiled against beside the dylibs so
# build-ios-app.sh and publish-ota.sh can refuse a stale pair.
"$ROOT/scripts/gen-version-header.sh"
VERSION_HASH="$("$ROOT/scripts/gen-version-header.sh" --print-hash)"

# Generated by a meson custom_target upstream; driven directly here — but from
# PRISTINE upstream at the pin rather than from our patched trees, and asserted
# against overlay/savegame-stamp.txt. Unconditionally, every build: the previous
# `if [ ! -f ... ]` cache made the stamp a function of whichever build ran first
# on the machine, so a clean tree silently invalidated every existing savegame
# (D-070's latent trap, closed by D-084).
"$ROOT/scripts/gen-savegame-compat-header.sh"
[ -f "$GEN/openq4_savegame_compat_generated.h" ] \
	|| { echo "FATAL: savegame compat header not generated" >&2; exit 1; }

# Support headers come from the ENGINE tree; only game/ and mpgame/ come from the
# staged gamelibs. The stage has no framework/ at all, and the game sources
# include "../framework/..." relative to idlib.
INCS=( -I"$GEN" -I"$TREE/src" -I"$TREE/src/idlib" -I"$TREE/src/renderer"
       -I"$TREE/src/ui" -I"$TREE/src/sys" -I"$TREE/src/bse" -I"$TREE/src/MayaImport"
       -I"$STAGE/src/game" -I"$STAGE/src/mpgame"
       -I"$TREE/subprojects/glew/include" -I"$TREE/src/external/vulkan/include"
       -I"$DEPS/sdl-prefix/include" -I"$DEPS/openal-prefix/include" )

DEFS=( -DUSE_OPENAL -DGLEW_NO_GLU -DID_GL_HARDLINK -DMACOS_X=1
       -DUSE_OPENAL_SOFT_INCLUDES=1 -DUSE_SDL3=1 -DGAME_DLL -DOPENQ4_IOS=1 )
# Same platform-define convention as the engine (D-089): visionOS keeps
# OPENQ4_IOS and adds its own. OPENQ4_SWIFT_MAIN is deliberately NOT set here —
# a game module has no entry point and must not diverge from the iOS build on
# anything but the target triple.
case "$LANE" in
	visionos|visionos-sim) DEFS+=( -DOPENQ4_VISIONOS=1 ) ;;
esac

# -fvisibility=hidden matches upstream's game-module targets. It is half of the
# isolation that lets two modules with conflicting type definitions coexist.
CXXFLAGS=( -isysroot "$SDK" "${TARGET_FLAGS[@]}"
           -std=c++17 -O2 -DNDEBUG -fno-strict-aliasing
           -fvisibility=hidden -fvisibility-inlines-hidden
           -Wno-everything
           -include "$TREE/src/idlib/precompiled.h" )

list_sources() { # <subdir>
	( cd "$TREE" && python3 tools/build/list_sources.py "$STAGE" "$1" \
		"$1/Callbacks.cpp" "$1/gamesys/Callbacks.cpp" 2>/dev/null )
}

build_module() { # <flavour: sp|mp>
	local flavour="$1"
	local gamedir extra=()
	if [ "$flavour" = mp ]; then gamedir=src/mpgame; extra=( -DGAME_MPAPI ); else gamedir=src/game; fi

	local objdir="$OUT/gameobj/$flavour"
	rm -rf "$objdir"; mkdir -p "$objdir"

	# idlib is rebuilt per flavour, NOT shared: -DGAME_MPAPI changes which
	# Game_local.h precompiled.h pulls in, which changes the types every idlib
	# TU sees. Sharing one build here is the ODR bug upstream documents.
	local srcs
	srcs="$(list_sources src/idlib)
$(list_sources "$gamedir")"
	local n; n=$(echo "$srcs" | grep -c . || true)
	echo "==> $flavour: compiling $n sources (idlib + $gamedir) for $LANE (-j$JOBS)"

	local wrap="$objdir/.compile.sh"
	{
		echo '#!/usr/bin/env bash'
		echo 'set -euo pipefail'
		printf 'STAGE=%q\nOBJDIR=%q\nCXX=%q\nLOGDIR=%q\n' "$STAGE" "$objdir" "$CXX" "$OUT/gamelogs"
		printf 'CXXFLAGS=('; printf '%q ' "${CXXFLAGS[@]}"; echo ')'
		printf 'DEFS=(';     printf '%q ' "${DEFS[@]}";     echo ')'
		printf 'EXTRA=(';    printf '%q ' ${extra[@]+"${extra[@]}"}; echo ')'
		printf 'INCS=(';     printf '%q ' "${INCS[@]}";     echo ')'
		cat <<'BODY'
src="$1"
obj="$OBJDIR/$(echo "$src" | tr '/' '_').o"
log="$LOGDIR/$(echo "$src" | tr '/' '_').log"
if ! "$CXX" -x c++ "${CXXFLAGS[@]}" "${DEFS[@]}" ${EXTRA[@]+"${EXTRA[@]}"} \
	"${INCS[@]}" -c "$STAGE/$src" -o "$obj" > "$log" 2>&1; then
	echo "FAILED $src" >&2
	grep -E 'error:' "$log" | head -5 >&2
	exit 1
fi
BODY
	} > "$wrap"
	chmod +x "$wrap"

	echo "$srcs" | grep . | xargs -P "$JOBS" -I{} "$wrap" {} \
		|| { echo "FATAL: $flavour compilation failed" >&2; exit 1; }

	local dylib="$MODOUT/game-${flavour}_arm64.dylib"
	echo "==> $flavour: linking $(basename "$dylib")"
	# -exported_symbols_list is upstream's own (darwin_game_module.exp): only
	# _GetGameAPI may be exported, because two modules exporting conflicting
	# definitions of the same names is "a loader-order lottery" (issue #90).
	# install_name is @rpath-based for bundle embedding; note the engine dlopens
	# by absolute path, so this matters only to the signing/embedding step.
	"$CXX" -dynamiclib "${CXXFLAGS[@]}" \
		-install_name "@rpath/$(basename "$dylib")" \
		-Wl,-exported_symbols_list,"$TREE/tools/build/darwin_game_module.exp" \
		-Wl,-dead_strip \
		-o "$dylib" "$objdir"/*.o \
		> "$OUT/gamelogs/link-$flavour.log" 2>&1 \
		|| { tail -25 "$OUT/gamelogs/link-$flavour.log"; echo "FATAL: $flavour link failed" >&2; exit 1; }

	# Ground rule 3: assert, do not assume. If anything but the entry point is
	# exported, the two modules can interpose each other at runtime and the
	# failure is silent state corruption rather than a link error.
	local exports
	exports="$(nm -gU "$dylib" 2>/dev/null | awk '{print $3}' | grep -v '^$' || true)"
	if [ "$(echo "$exports" | grep -c .)" -ne 1 ] || [ "$(echo "$exports" | tr -d ' ')" != "_GetGameAPI" ]; then
		echo "FATAL: $(basename "$dylib") must export exactly _GetGameAPI, got:" >&2
		echo "$exports" | head -20 >&2
		exit 1
	fi
	echo "    $(basename "$dylib")  $(ls -lh "$dylib" | awk '{print $5}')  exports: _GetGameAPI only"
}

case "$WHICH" in
	sp)   build_module sp ;;
	mp)   build_module mp ;;
	both) build_module sp; build_module mp ;;
	*) echo "usage: $0 [device|sim|visionos|visionos-sim] [sp|mp|both]" >&2; exit 1 ;;
esac

# Only a complete pair is a valid stamp: stamping after `sp` alone would claim
# the mp module is current when it was built against an older header.
if [ "$WHICH" = both ]; then
	echo "$VERSION_HASH" > "$MODOUT/.version-header-sha256"
else
	rm -f "$MODOUT/.version-header-sha256"
	echo "!! built only '$WHICH' — the module stamp is cleared; run '$0 $LANE both' before shipping" >&2
fi

echo
echo "IOS GAME MODULES OK ($LANE)"
ls -lh "$MODOUT"/*.dylib | awk '{print "  " $9 "  " $5}'
